### ISSUE TITLE
Inquiry About Dataset Release Date

### ISSUE THREAD

**Issue by joy0x1** [zhuyr97/Reflection_RemoVal_CVPR2024#1]
Hello,

I am interested in the RRW dataset, and I would like to inquire about its release date. Could you please provide information on when the dataset will be released?

Thank you for your assistance!

请问大概什么时候会公布数据集呢？可以麻烦您给一个时间吗？非常感谢！ @zhuyr97

**Comment by zhuyr97** [comment]
Released!
