### ISSUE TITLE
关于networks/efficientnet_pytorch/utils.py 中包含绝对路径

### ISSUE THREAD

**Issue by 634085586** [zhuyr97/Reflection_RemoVal_CVPR2024#2]
目前 networks/efficientnet_pytorch/utils.py 中包含个人路径，导致找不到对应模型，无法跑通
改为如下代码后可跑通
`import os.path as osp

cur_dir = osp.abspath(osp.join(__file__,osp.pardir, osp.pardir))
model_path = osp.join(cur_dir,'efficientB3/')
`

**Comment by zhuyr97** [comment]
Thanks!
